

#doan nay la de cho bitbake biet file metadata này o dau sau nay no can dung den bien BBPATH
BBPATH .= ":${LAYERDIR}"


#doan nay là de scan tat ca cac file .bb va .bbappend sau no chi can goi bien BBFILES lai

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

#dinh danh layer de bitbake biet thuoc layer nao
BBFILE_COLLECTIONS += "meta-okmx6ull"

#sau khi dinh danh song bitbake can biet duong dan cua no
BBFILE_PATTERN_meta-okmx6ull = "^${LAYERDIR}/"
# nếu nhiều layer/recipe/metadata conflict thì ưu tiên layer priority cao hơn
BBFILE_PRIORITY_meta-okmx6ull = "10"

#no se khai bao dung lai nhung thu cua core nhu cac ham, cac bien core da viet san 
LAYERDEPENDS_meta-okmx6ull = "core"

#khai bao cho biet su dung version nao, moi vison se co cu phap khac nhau
LAYERSERIES_COMPAT_meta-okmx6ull = "kirkstone"
