
MACHINEOVERRIDES =. "mx6:mx6ul:mx6ull:"

include conf/machine/include/imx-base.inc
include conf/machine/include/arm/armv7a/tune-cortexa7.inc

# Chỉ định kernel device tree cho board
KERNEL_DEVICETREE = "imx6ull-14x14-evk-emmc.dtb"

# Chọn U-Boot config mặc định cho machine
UBOOT_CONFIG ?= "emmc"

# emmc:
# - dùng U-Boot defconfig mx6ull_14x14_evk_emmc_config
# - dùng boot media/layout kiểu sdcard (MMC/eMMC)
UBOOT_CONFIG[emmc] = "okmx6ull_s_emmc_defconfig,sdcard"

# Serial console UART1
SERIAL_CONSOLES = "115200;ttymxc0"