
#doi sag machine cua minh
#de bitbake biet build cho board nao
MACHINE ??= 'okmx6ull-s-emmc'

#build theo distro config nào
DISTRO ?= 'fsl-imx-fb'

PACKAGE_CLASSES ?= 'package_rpm'

#gop lại nhieu tien ich cho dev de dung ssh khong can password, 
# tham khao tai trang https://docs.yoctoproject.org/4.1/ref-manual/features.html
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"

#bat tinh nang thoi gian ghi lại tung task xem hoan thanh trong bao lau 
USER_CLASSES ?= "buildstats"

#qua trinh build co pacth bi loi thi bo qua build not 
PATCHRESOLVE = "noop"

#bao ve khi build
#VD: STOPTASKS,${TMPDIR},1G,100K la con duoi 1G dung nhan task moi
#VD: HALT,${TMPDIR},100M,1K la con duoi 100M thi dung han cac task
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    HALT,${TMPDIR},100M,1K \
    HALT,${DL_DIR},100M,1K \
    HALT,${SSTATE_DIR},100M,1K \
    HALT,/tmp,10M,1K"

#khi build song co the dung do hoa test tren may ao truoc
PACKAGECONFIG:append:pn-qemu-system-native = " sdl"

#check xem phien ban yocto dung hay chua # Yocto 4.1 → CONF_VERSION = "2" check xem 
#neu yocto dang la vesion 2 vơi version 1 se khac nhau nó check day de bao loi
CONF_VERSION = "2"

#chi dinh nhưng cai tai ve khi  build
DL_DIR ?= "${BSPDIR}/downloads/"
ACCEPT_FSL_EULA = "1"

# nghia la cac goi sau khi build song deu được nen thanh .deb sau do addd vapf rootfs 
PACKAGE_CLASSES = "package_deb"

#thêm feature vào rootfs
EXTRA_IMAGE_FEATURES += "package-management"


#them vao userspace cac goi nhu kernel-modules de co the nhet file .ko vao image
#iw la co the scan wifi va ket noi wifi thong qua wpa-supplicant
#usbutils co the xem dươc usb o tang userspace
IMAGE_INSTALL:append = " kernel-modules iw wpa-supplicant usbutils"

#dùng layout partition nào để tạo .wic
WKS_FILE = "okmx6ull-forlinx.wks"

#output cần build ra là gì
IMAGE_FSTYPES = "wic wic.zst tar.zst"

#build DTB nào từ kernel source
KERNEL_DEVICETREE = "imx6ull-14x14-evk-emmc.dtb"

#copy file nào vào boot partition FAT 
#copy vao chuan cac phan vung de no khop voi emmc dang chia de no biet boot nhu nao

IMAGE_BOOT_FILES = " \
    zImage \
    zImage;zImage_A \
    zImage;zImage_B \
    imx6ull-14x14-evk-emmc.dtb \
    imx6ull-14x14-evk-emmc.dtb;imx6ull-14x14-evk.dtb \
    boot.scr \
"

#bitbake ota-boot-script    
# chạy trước
#→ tạo ra boot.scr

#bitbake core-image-minimal # chạy sau
#   → dùng boot.scr để tạo image
#  → boot.scr vào boot partition (qua IMAGE_BOOT_FILES)
# → rootfs không chứa ota-boot-script
EXTRA_IMAGEDEPENDS += "ota-boot-script"

BB_NUMBER_THREADS = "8"
PARALLEL_MAKE = "-j8"
PARALLEL_MAKEINST = "-j8"
IMAGE_INSTALL:append = " rtl8723du"

#them ssh 
IMAGE_INSTALL:append = " openssh openssh-sshd openssh-sftp-server"
EXTRA_IMAGE_FEATURES += "ssh-server-openssh"

#quan ly start, stop network luc boot, them files interface de config network
IMAGE_INSTALL:append = " init-ifupdown"
#tu dong ket noi wifi luc boot
IMAGE_INSTALL:append = " wlan0-autostart"

#them mqtt mosquito
IMAGE_INSTALL:append = " mosquitto mosquitto-clients"
SYSTEMD_AUTO_ENABLE:pn-mosquitto = "enable"

#them app HNN OKM6ULL OTA
IMAGE_INSTALL:append = " hnn-okm6ull-ota"

#them lib fw_setenv
IMAGE_INSTALL:append = " libubootenv-bin"

#them config cho evn 
IMAGE_INSTALL:append = " u-boot-env-config"


IMAGE_INSTALL:append = " zstd"


IMAGE_INSTALL:append = " e2fsprogs e2fsprogs-mke2fs"
