
#doi sag machine cua minh
#de bitbake biet build cho board nao
MACHINE ??= 'okmx6ull-s-emmc'
#build theo distro config nào
DISTRO ?= 'fsl-imx-fb'

PACKAGE_CLASSES ?= 'package_rpm'
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
USER_CLASSES ?= "buildstats"
PATCHRESOLVE = "noop"
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    HALT,${TMPDIR},100M,1K \
    HALT,${DL_DIR},100M,1K \
    HALT,${SSTATE_DIR},100M,1K \
    HALT,/tmp,10M,1K"
PACKAGECONFIG:append:pn-qemu-system-native = " sdl"
CONF_VERSION = "2"

DL_DIR ?= "${BSPDIR}/downloads/"
ACCEPT_FSL_EULA = "1"

# Switch to Debian packaging and include package-management in the image
#rootfs dùng package format gì
PACKAGE_CLASSES = "package_deb"

#thêm feature vào rootfs
EXTRA_IMAGE_FEATURES += "package-management"

IMAGE_INSTALL:append = " kernel-modules iw wpa-supplicant usbutils"

#dùng layout partition nào để tạo .wic
WKS_FILE = "okmx6ull-forlinx.wks"

#output cần build ra là gì
IMAGE_FSTYPES = "wic wic.zst tar.zst"

#build DTB nào từ kernel source
KERNEL_DEVICETREE = "imx6ull-14x14-evk-emmc.dtb"

#copy file nào vào boot partition FAT

IMAGE_BOOT_FILES = " \
    zImage \
    imx6ull-14x14-evk-emmc.dtb \
    imx6ull-14x14-evk-emmc.dtb;imx6ull-14x14-evk.dtb \
"

BB_NUMBER_THREADS = "4"
PARALLEL_MAKE = "-j4"
PARALLEL_MAKEINST = "-j4"
IMAGE_INSTALL:append = " rtl8723du"


IMAGE_INSTALL:append = " openssh openssh-sshd openssh-sftp-server"



EXTRA_IMAGE_FEATURES += "ssh-server-openssh"


IMAGE_INSTALL:append = " init-ifupdown"
